development:
  adapter:  mysql2
  encoding: utf8
  database: template_develop
  username: root
  password: root

test:
  adapter:  mysql2
  encoding: utf8
  database: template_test
  username: root
  password: root

production:
  adapter:  mysql2
  encoding: utf8
  database: template_production
  username: root
  password: root
